# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alura_Viagens_SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alura_Viagens_SwiftUI

  target 'Alura_Viagens_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Alura_Viagens_SwiftUIUITests' do
    # Pods for testing
  end

end
